[package]
name = "simple_test"
version.workspace = true
edition.workspace = true

[dev-dependencies]
bare-test = { workspace = true }
log = { workspace = true }

[build-dependencies]
bare-test-macros = { workspace = true }
